#!/usr/bin/env sh

# necessary to load scripting-addition during startup on macOS Big Sur
# *yabai --load-sa* is configured to run through sudo without a password
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
# yabai -m config external_bar                 all:24:0
yabai -m config mouse_follows_focus          on 
yabai -m config focus_follows_mouse          autofocus 
yabai -m config window_placement             second_child
yabai -m config window_topmost               on 
yabai -m config window_opacity               on 
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                off 
yabai -m config insert_feedback_color        0xaad75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off 
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  8 
yabai -m config bottom_padding               8
yabai -m config left_padding                 8
yabai -m config right_padding                8 
yabai -m config window_gap                   8

# rules
## makes system preferences always floating
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Wally$" manage=off
yabai -m rule --add app="^Pulse Secure$" manage=off

# signals
yabai -m signal --add event=window_destroyed active=yes action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null"
yabai -m signal --add event=window_minimized active=yes action="if \$(yabai -m query --windows --window \$YABAI_WINDOW_ID | jq -r '.\"is-floating\"'); then yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null; fi"

echo "yabai configuration loaded.."
