theme = "modern"
icons = "awesome"

[[block]]
block = "battery"
interval = 120

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 360
format = "%d.%m."

[[block]]
block = "time"
interval = 60
format = "%R"

