name: xmonad-andys8
version: 0.1.0
synopsis: xmonad setting
github: andys8/dotfiles
author: andys8
maintainer: andys8@99n.de
copyright: © andys8
license: MIT
dependencies:
  - X11
  - base
  - containers
  - mtl
  - transformers
  - xmonad
  - xmonad-contrib
executables:
  xmonad:
    main: xmonad.hs
    ghc-options:
      - -Wall
      - -fwarn-tabs
      - -fno-warn-missing-signatures
      - -Wno-name-shadowing
      - -threaded
      - -O2
      - -with-rtsopts=-N4
