name: CI
on: [push]
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install shellcheck
        run: sudo apt-get install shellcheck -y
      - name: Run shellcheck
        run: shellcheck **/*.sh

